apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crc-impersonation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crc-impersonation
  minReplicas: {{ (index (index .Values.sizeMap (required "size is required" .Values.size)) "crc-impersonation").min | default 1 }}
  maxReplicas: {{ (index (index .Values.sizeMap (required "size is required" .Values.size)) "crc-impersonation").max | default 4 }}
  targetCPUUtilizationPercentage: 75
