# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
config:
  isDev: false
  name: 'ricky-chart'

sizeMap:
  small:
    access-control:
      min: 1
      max: 1
    business-data-integration:
      min: 1
      max: 1
    cluster-paths-router:
      min: 1
      max: 1
    school-api-gateway:
      min: 1
      max: 1
    crc-api-gateway:
      min: 1
      max: 1
    login-controller:
      min: 1
      max: 1
    old-house-mobile-login:
      min: 1
      max: 1

size: small
supportedIDPs: [{
  code: "DEV_AUTH",
  clientIdSecretName: "keycloak-client-id",
  clientSecretSecretName: "keycloak-client-secret",
  authorizeEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/auth",
  tokenRequestEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/token",
  logoutRequestEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/logout",
  businessDataApi: "http://keycloak-bs-api.infrastructure.svc.cluster.local",
  houseDispatcherApi: "http://keycloak-bs-api.infrastructure.svc.cluster.local",
  houseDispatcherApiKeySecretName: "keycloak-house-dispatcher-api-key"
},
{
  code: "QA_AUTH",
  clientIdSecretName: "keycloak-client-id",
  clientSecretSecretName: "keycloak-client-secret",
  authorizeEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/auth",
  tokenRequestEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/token",
  logoutRequestEndpoint: "https://dev-learn.corporate.ef.com/dev-auth/auth/realms/development/protocol/openid-connect/logout",
  businessDataApi: "http://keycloak-bs-api.infrastructure.svc.cluster.local",
  houseDispatcherApi: "http://keycloak-bs-api.infrastructure.svc.cluster.local",
  houseDispatcherApiKeySecretName: "keycloak-house-dispatcher-api-key"
}]

loginControllerPublicHost: 'https://www.baidu.com'
schoolPublicUrl: 'https://learn.corporate.ef.com/'
imageVersions:
  loginController: 1.0.38
services:
  account: 'https://learn.corporate.ef.com/account'
  accessControl: 'https://learn.corporate.ef.com/accessControl'
  operatorsManagement: 'https://learn.corporate.ef.com/operatorManagement'
  enrollmentsManagement: 'https://learn.corporate.ef.com/enrollmentMangement'
  businessDataIntegration: 'https://learn.corporate.ef.com/businessDataIntegration'

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
